### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by IstoraMandiri** [SilentCicero/meteor-package-ipfsapi#1]
I'm having problems getting this working. Using latest version with meteor 1.2.1, `silentcicero:ipfs-api` adds the following to `versions`

```
silentcicero:ipfs-api@2.13.2-5
```

And prevents meteor from starting with 

```
=> Started proxy.
=> Meteor 1.3 is available. Update this project with 'meteor update'.
=> Started MongoDB.
W20160403-21:26:33.537(1)? (STDERR)
W20160403-21:26:33.538(1)? (STDERR) /Users/chris/.meteor/packages/meteor-tool/.1.1.10.rp7nbh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160403-21:26:33.539(1)? (STDERR)             throw(ex);
W20160403-21:26:33.539(1)? (STDERR)                   ^
W20160403-21:26:33.539(1)? (STDERR) Error: Can't find npm module 'ipfsAPI'. Did you forget to call 'Npm.depends' in package.js within the 'silentcicero_ipfs-api' package?
W20160403-21:26:33.539(1)? (STDERR)     at Object.Npm.require (/Users/chris/git/projects/dapp-workshop/app/.meteor/local/build/programs/server/boot.js:175:17)
W20160403-21:26:33.539(1)? (STDERR)     at Package (package-init.js:8:78)
W20160403-21:26:33.539(1)? (STDERR)     at /Users/chris/git/projects/dapp-workshop/app/.meteor/local/build/programs/server/packages/silentcicero_ipfs-api.js:38:4
W20160403-21:26:33.539(1)? (STDERR)     at /Users/chris/git/projects/dapp-workshop/app/.meteor/local/build/programs/server/packages/silentcicero_ipfs-api.js:47:3
W20160403-21:26:33.539(1)? (STDERR)     at /Users/chris/git/projects/dapp-workshop/app/.meteor/local/build/programs/server/boot.js:242:10
W20160403-21:26:33.542(1)? (STDERR)     at Array.forEach (native)
W20160403-21:26:33.542(1)? (STDERR)     at Function._.each._.forEach (/Users/chris/.meteor/packages/meteor-tool/.1.1.10.rp7nbh++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160403-21:26:33.542(1)? (STDERR)     at /Users/chris/git/projects/dapp-workshop/app/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

**Comment by RamiroMoreira** [comment]
im having the same issue
